import { useEffect, useState } from "react";
import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { listPublicProducts, type Product } from "../lib/supabase-data";
type OrderItem = { productId: string; quantity: number };
const ORDER_KEY = "adson-fashion-cart";
function readOrder(): OrderItem[] { try { return JSON.parse(localStorage.getItem(ORDER_KEY) ?? "[]") as OrderItem[]; } catch { return []; } }
function writeOrder(items: OrderItem[]) { localStorage.setItem(ORDER_KEY, JSON.stringify(items)); }
export const Route = createFileRoute("/produtos")({ component: ProductsPage });
function ProductsPage() {
  const navigate = useNavigate(); const [products, setProducts] = useState<Product[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [order, setOrder] = useState<OrderItem[]>([]);
  useEffect(() => { setOrder(readOrder()); let active = true; void listPublicProducts().then((data) => { if (active) setProducts(data); }).catch((e) => { if (active) setError(e instanceof Error ? e.message : "Não foi possível carregar os produtos."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  function selectProduct(product: Product) { const existing = order.find((item) => item.productId === product.id); const next = existing ? order.map((item) => item.productId === product.id ? { ...item, quantity: Math.min(item.quantity + 1, product.stock) } : item) : [...order, { productId: product.id, quantity: 1 }]; setOrder(next); writeOrder(next); }
  function removeProduct(productId: string) { const next = order.filter((item) => item.productId !== productId); setOrder(next); writeOrder(next); }
  function quantity(productId: string) { return order.find((item) => item.productId === productId)?.quantity ?? 0; }
  const itemCount = order.reduce((sum, item) => sum + item.quantity, 0);
  const total = order.reduce((sum, item) => { const product = products.find((p) => p.id === item.productId); return sum + (product ? Number(product.price) * item.quantity : 0); }, 0);
  return (<main className="min-h-screen bg-slate-50 pb-24 text-slate-950">
    <header className="sticky top-0 z-20 border-b border-slate-200 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between gap-3 px-4 py-3 sm:px-6"><button type="button" onClick={() => navigate({ to: "/" })} className="text-left"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-slate-500">Adson Fashion</p><p className="text-base font-black">Produtos</p></button>{itemCount > 0 && <button type="button" onClick={() => navigate({ to: "/checkout" })} className="rounded-lg bg-slate-950 px-3 py-2 text-xs font-bold text-white">Encomenda · {itemCount}</button>}</div></header>
    <section className="mx-auto max-w-6xl px-4 py-6 sm:px-6 sm:py-8"><div className="mb-5"><p className="text-xs font-bold uppercase tracking-[0.16em] text-slate-500">Catálogo</p><h1 className="mt-1.5 text-2xl font-black tracking-tight sm:text-3xl">Escolha o que deseja encomendar</h1><p className="mt-2 max-w-2xl text-sm leading-5 text-slate-600">Escolha um ou vários produtos. Quando terminar, toque em <strong>Fazer encomenda</strong>.</p></div>
      {error && <div className="mb-5 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-xs font-medium text-red-700">{error}</div>}
      {loading ? <div className="rounded-xl bg-white p-8 text-center text-sm text-slate-500">A carregar produtos...</div> : products.length === 0 ? <div className="rounded-xl border border-dashed border-slate-300 bg-white p-8 text-center"><p className="text-3xl">🛍️</p><h2 className="mt-3 text-base font-black">Ainda não há produtos</h2><p className="mt-1 text-xs text-slate-500">Os produtos adicionados pelo ADM aparecerão aqui.</p></div> : <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4 sm:gap-4">{products.map((product) => { const selected = quantity(product.id); return <article key={product.id} className={`overflow-hidden rounded-xl border bg-white shadow-sm transition ${selected > 0 ? "border-slate-950 ring-1 ring-slate-950/10" : "border-slate-200"}`}><div>{product.image_url ? <img src={product.image_url} alt={product.name} className="h-40 w-full object-cover sm:h-52" /> : <div className="flex h-40 items-center justify-center bg-slate-100 text-3xl sm:h-52">🛍️</div>}</div><div className="p-3 sm:p-4"><p className="truncate text-[10px] font-bold uppercase tracking-wider text-slate-500">{product.category}</p><h2 className="mt-1 truncate text-sm font-black">{product.name}</h2><p className="mt-2 text-base font-black">{Number(product.price).toLocaleString("pt-MZ")} MT</p><p className={product.stock > 0 ? "mt-1 text-[11px] font-semibold text-emerald-600" : "mt-1 text-[11px] font-semibold text-red-600"}>{product.stock > 0 ? `${product.stock} disponíveis` : "Esgotado"}</p><button type="button" disabled={product.stock <= 0} onClick={() => selectProduct(product)} className={`mt-3 w-full rounded-lg px-3 py-2.5 text-xs font-bold transition ${selected > 0 ? "bg-emerald-600 text-white" : "bg-slate-950 text-white"} disabled:cursor-not-allowed disabled:bg-slate-200 disabled:text-slate-400`}>{selected > 0 ? `✓ Selecionado · ${selected}` : "Fazer encomenda"}</button>{selected > 0 && <button type="button" onClick={() => removeProduct(product.id)} className="mt-1.5 w-full py-1.5 text-[11px] font-semibold text-slate-500 hover:text-red-600">Remover</button>}</div></article>; })}</div>}
    </section>
    {itemCount > 0 && <div className="fixed inset-x-0 bottom-0 z-30 border-t border-slate-200 bg-white/95 p-3 shadow-xl backdrop-blur"><div className="mx-auto flex max-w-4xl items-center justify-between gap-3"><div><p className="text-xs font-bold text-slate-500">{itemCount} {itemCount === 1 ? "item" : "itens"}</p><p className="text-base font-black">{total.toLocaleString("pt-MZ")} MT</p></div><button type="button" onClick={() => navigate({ to: "/checkout" })} className="rounded-lg bg-slate-950 px-4 py-2.5 text-xs font-bold text-white">Fazer encomenda →</button></div></div>}
  </main>);
}